### ISSUE TITLE
Notification Center does not show the message, only the title

### ISSUE THREAD

**Issue by BerndGewehr** [ibmcnxdev/cnx-custom-theme#15]
In the visual update 1 for Connections cloud, the notification center does not show the message of a post, only the titel. Please care for showing the message also!
![2017-12-30 16_46_30-microsoft edge](https://user-images.githubusercontent.com/21081707/34455513-0e271166-ed81-11e7-9517-278a957cbb18.png)
![2017-12-30 16_46_14-microsoft edge](https://user-images.githubusercontent.com/21081707/34455514-0e3f25f8-ed81-11e7-90e5-fbe95e4ecbc5.png)

**Comment by heinsj** [comment]
@BerndGewehr Thanks for the feedback. What are these updates showing? Are these status updates or comments on a wiki?

**Comment by bgewehr** [comment]
If you comment on a wiki, the comment is shown in old style and only the title in the new style. Also when you post to the activity stream via API the message body is shown in old style and only the title in the new style.

**Comment by heinsj** [comment]
@BerndGewehr Thanks for reporting this. We have fixed it and the fix will be included in the late January update.

**Comment by BerndGewehr** [comment]
Fixed
