### ISSUE TITLE
CSS Issue / Safari on MacOs High Sierra / Share file dialog box

### ISSUE THREAD

**Issue by DanieleVistalli** [ibmcnxdev/cnx-custom-theme#26]
### Steps to reproduce the issue

1. Using Safari on MacOs High Sierra
1. Access Connections files
1. Click "more" (left of the file entry in the file listing)
1. Click "share ..." to thare the file
1. The "share file" dialog box is shonw
1. The field where you can type-ahead the name of the person you want to share with is not visible

It works (field to select user to share with) is shown.

**Comment by heinsj** [comment]
@DanieleVistalli Have you only see this issue on Safari or is it a general problem?
I see this in Chrome:
![image](https://user-images.githubusercontent.com/33330856/37435637-72b52366-27ba-11e8-86aa-c8ac07cb8ae0.png)

**Comment by DanieleVistalli** [comment]
We only got the issue on safari (a colleague reported it to me with screenshots). 

I just re-checked:

- Chrome on Windows 10
- Firefox on Windows 10 (latest, non ESR)
- IE 11 on Windows 10
- Microsoft Edge on Windows 10

Everything is fine only Safari/MacOS appears to be failing.

![image](https://user-images.githubusercontent.com/4408708/37449314-17a04620-282a-11e8-9e97-9e23f504f8e5.png)

As you see in the screenshot after the "access level" drop down there's no Person name or email but immediately the comment/optional message.

Screeonshot is taken on MacOS / Sierra

**Comment by heinsj** [comment]
We have a fix for this. I am testing it on a staging server now and hope to have it published this week. I will update this once pushed.

**Comment by heinsj** [comment]
@DanieleVistalli I have just deployed a fix for this. You should now see the Person name or email field when sharing a file in Safari. See more information about what else changed in this Update History page: https://hclcnx.github.io/cnx-custom-theme/updatehistory.html
